language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

branches:
  only:
    - master

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_install:
  - if [[ "$TRAVIS_PHP_VERSION"  = "hhvm" ]]; then cat travis.php.ini >> /etc/hhvm/php.ini ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-add travis.php.ini ; fi
  - composer self-update

install:
  - composer install --prefer-source --profile

script: if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi

after_script:
  - if [ -e coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ -e coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
